### ISSUE TITLE
Notebook is already great, some lights comments

### ISSUE THREAD

**Issue by canyon289** [symeneses/SBM#6]
As title says this is already really good. Some suggestions

1. Add a quick readme at the top that says how to use this notebook. 
2. Great job with dist_validator
  * Maybe another thing is if handler returns a dictionary of infdata objects. It already might I'm just not sure
3. Template is spelled wrong in the colab link causing a link failure

Can I share this with the pymc team? They may have suggestions as well

https://github.com/symeneses/SBM/blob/main/notebooks/template.ipynb

**Comment by symeneses** [comment]
Thank you for your comments:

1. Instructions will be added once the option to work with multiple data sizes is done.
2. I got the basic idea for the `dist_validator` talking with @OriolAbril. So, credit goes to him.
3. 'infer_data' is a dictionary with the InferData objects with the `library_sampler` as key.
4. Typo fixed, the template is now opening with Colab.

Of course, you can share this. The more feedback the better.
